### ISSUE TITLE
Building on Linux (Ubuntu)

### ISSUE THREAD

**Issue by CyberPlaton** [fountainment/cherrysoda-engine#2]
I have issues building on Ubuntu Linux.

As I run the command "cmake --build . --config Release" it builds up to 43% and in the file "Interface/Window.cpp" it says "union SDL_SysWMinfo has no member named 'x11'" at 415
``return (void*)wmi.info.x11.window;``
and at 446
``return (void*)wmi.info.x11.display;``

Beforehand I have installed needed libraries as specified in the workflow file "linux.yml".

I tried to resolve the issues for the last two days now but nothing helps, maybe You have an idea.

**Comment by fountainment** [comment]
Can you give some more information on which version of the system and which version of SDL.
I have no clue on this issue, but maybe you can try compiling the SDL library from scratch https://github.com/libsdl-org/SDL.

**Comment by fountainment** [comment]
![图片](https://user-images.githubusercontent.com/8925165/149649018-f313f858-21eb-48db-8045-076bf7d1095f.png)

Because you didn't provide the system version, I can only guess that you're using the latest ubuntu LTS version 20.04, I personally use manjaro linux, so the test is done on VM. It shows that the engine compiles correctly on Ubuntu 20.04.3 LTS.

**Comment by fountainment** [comment]
And please have a look at https://github.com/fountainment/cherrysoda-engine/issues/3, if you're using ubuntu 21.04 or later.

**Comment by CyberPlaton** [comment]
My version of Ubuntu 20.04.3 LTS. And "echo $XDG_SESSION_TYPE" returns "x11". But Ive seen that my SDL2 version is libsdl2-2.0-0:amd64 2.0.10+dfsg1-3. So maybe I try building SDL2 from scratch and replay later. Thank you!

**Comment by CyberPlaton** [comment]
Alright, it seems that previously I configured cmake not correctly, so now I followed exactly the steps described in the README and was able to build the engine on linux. Sorry for the trouble.
